name: humoji_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  emoji_picker_flutter: ^1.5.1
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/telugu songs/
    - assets/hindi songs/
    - assets/english songs/
    - assets/tamil songs/
